
package cn.itcast.hello;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://hello.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://hello.itcast.cn/", className = "cn.itcast.hello.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://hello.itcast.cn/", className = "cn.itcast.hello.GetDataResponse")
    @Action(input = "http://hello.itcast.cn/HelloService/getDataRequest", output = "http://hello.itcast.cn/HelloService/getDataResponse")
    public String getData();

}
