
package cn.itcast.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServiceImpl", targetNamespace = "http://service.itcast.cn/")
@XmlSeeAlso({
})
public interface PersonServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://service.itcast.cn/", className = "cn.itcast.service.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.itcast.cn/", className = "cn.itcast.service.GetDataResponse")
    @Action(input = "http://service.itcast.cn/PersonServiceImpl/getDataRequest", output = "http://service.itcast.cn/PersonServiceImpl/getDataResponse")
    public String getData();

}
