
package com.baidu.so.soso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServiceImpl", targetNamespace = "http://service.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.baidu.so.soso.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPersonById", targetNamespace = "http://service.itcast.cn/", className = "com.baidu.so.soso.FindPersonById")
    @ResponseWrapper(localName = "findPersonByIdResponse", targetNamespace = "http://service.itcast.cn/", className = "com.baidu.so.soso.FindPersonByIdResponse")
    @Action(input = "http://service.itcast.cn/PersonServiceImpl/findPersonByIdRequest", output = "http://service.itcast.cn/PersonServiceImpl/findPersonByIdResponse")
    public Person findPersonById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
